### ISSUE TITLE
File size not being displayed in web interface

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/perma-capture#24]
![image](https://user-images.githubusercontent.com/2140548/101670792-a286b100-3a21-11eb-8872-2ba49e66664c.png)

**Comment by rebeccacremona** [comment]
Evidently it takes some time. I bet if you check again, now, the sizes will be there.

**Comment by rebeccacremona** [comment]
(which is not to say that we shouldn't improve that: why does it take so long?)

**Comment by abziegler** [comment]
Indeed, some time and a refresh seems to do the trick. From a naive pov, it seems a little weird to permit download, replay, etc. before being able to display size of the file
