### ISSUE TITLE
Unable to capture plain tweet

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/perma-capture#27]
https://twitter.com/engineers_feed/status/1338876470144458755

![image](https://user-images.githubusercontent.com/2140548/102239749-30044e00-3ec5-11eb-8eb2-7020b60ee41c.png)

also:

https://twitter.com/BeschlossDC/status/1338855594258

**Comment by rebeccacremona** [comment]
Weird:
![image](https://user-images.githubusercontent.com/11020492/102243885-adca5880-3ec9-11eb-8188-8e742b4a8d47.png)

**Comment by rebeccacremona** [comment]
The profile is still in the bucket at that location:
![image](https://user-images.githubusercontent.com/11020492/102244581-790ad100-3eca-11eb-938d-7a1eefb48969.png)

**Comment by rebeccacremona** [comment]
Here is where init-profile is defined.... https://github.com/webrecorder/browserkube/blob/41ccddb0f634e3e112a3480bc06277fe0c491a09/templates/browser-job.yaml#L51

And I note that I did -not- make this image name customizable yet, for use with our own registry.

**Comment by rebeccacremona** [comment]
Amazing!!!!!!!

The latest release of minio/mc image does not include tar
Last release:
```
docker run -it --rm --entrypoint /bin/sh minio/mc:RELEASE.2020-11-25T23-04-07Z
/ # which tar
/bin/tar
```
Most recent release:
```
docker run -it --rm --entrypoint /bin/bash minio/mc:RELEASE.2020-12-10T01-26-17Z
[root@33f1205d56db /]# which tar
bash: which: command not found
[root@33f1205d56db /]# tar
bash: tar: command not found
[root@33f1205d56db /]# /usr/bin/tar
bash: /usr/bin/tar: No such file or directory
[root@33f1205d56db /]# /bin/tar
bash: /bin/tar: No such file or directory
[root@33f1205d56db /]# find / -name tar
bash: find: command not found
```

**Comment by rebeccacremona** [comment]
Okay, this will take a PR to Browserkube and a new Helm chart to fix. I'll work on that shortly.

**Comment by ikreymer** [comment]
Nice find! We could just use an older version of the `minio/mc` image that has tar for now..

**Comment by rebeccacremona** [comment]
Fixed on stage. I'll close when we deploy to prod.

**Comment by rebeccacremona** [comment]
Okay: should be good to go! Note: the second twitter link supplied as an example is now 404......
